const ADD_INVOICE = 'ADD_INVOICE';
const REMOVE_INVOICE = 'REMOVE_INVOICE';
const UPDATE_NAME = 'UPDATE_NAME';
const UPDATE_QTY = 'UPDATE_QTY';
const UPDATE_PRICE = 'UPDATE_PRICE';

export {ADD_INVOICE, REMOVE_INVOICE, UPDATE_NAME, UPDATE_QTY, UPDATE_PRICE};
